### ISSUE TITLE
Add OnDeallocate callback

### ISSUE THREAD

**Issue by kyleburnette** [fullgrowngaming/Project-Oceanside#5]
When certain nodes are deallocated, certain things need to happen depending on that node's type and attributes. OnDeallocate will contain the logic to handle deallocating nodes of different types and with varying attributes

Example of something that can be handled this way: 
-enemies dying and dropping things (tokens, magic drops, etc.)

**Comment by geekbozu** [comment]
We need to ensure that OnDeallocate understands the difference between a room change and a Deallocate, 

For example

If we have bomb allocate smoke when it gets de-allocated that works for when a bomb expires, 
However this is different then a room change where smoke will never get allocated. 

The above example may not apply as we are emulating the state of the heap not necessarily the full timeline of the heap. So something else to keep in mind while defining these CallBacks
